# Generated by Django 3.1.4 on 2020-12-31 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='board_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='divisions.boarddefinition'),
        ),
        migrations.AddField(
            model_name='board',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='divisions.agedivision'),
        ),
        migrations.AddField(
            model_name='board',
            name='weight_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='divisions.weightclass'),
        ),
        migrations.AddConstraint(
            model_name='agedivision',
            constraint=models.CheckConstraint(check=models.Q(('lower_bound__lt', django.db.models.expressions.F('upper_bound')), ('upper_bound', 0), _connector='OR'), name='age_range'),
        ),
        migrations.AddConstraint(
            model_name='agedivision',
            constraint=models.UniqueConstraint(fields=('lower_bound', 'upper_bound'), name='unique_age_range'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.CheckConstraint(check=models.Q(value__gt=0), name='value_gt0'),
        ),
        migrations.AddConstraint(
            model_name='board',
            constraint=models.UniqueConstraint(fields=('board_definition', 'division', 'weight_class'), name='unique_board'),
        ),
    ]
