# Generated by Django 3.1.4 on 2020-12-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightclass',
            name='unbound',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates that this weight class\nhas no upper bound. Instead, you must weight at least the\namount specified by the upper bound field.'),
        ),
    ]
