# Generated by Django 3.1.4 on 2020-12-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0002_auto_20201220_2302'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weightclass',
            name='unique_weight_range',
        ),
        migrations.AddConstraint(
            model_name='weightclass',
            constraint=models.UniqueConstraint(fields=('lower_bound', 'upper_bound', 'gender'), name='unique_weight_range'),
        ),
    ]
