# Generated by Django 3.1.4 on 2020-12-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0002_weightclass_unbound'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='weightclass',
            name='unique_weight_class',
        ),
        migrations.AddConstraint(
            model_name='weightclass',
            constraint=models.UniqueConstraint(fields=('upper_bound', 'gender', 'unbound'), name='unique_weight_class'),
        ),
    ]
