# Generated by Django 3.1.4 on 2020-12-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divisions', '0003_auto_20201220_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarddefinition',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
