version: "3.8"
services:
    app:
        build:
            context: ../
        ports:
            - 3000:3000
        networks:
            - backend
    db:
        image: postgres:13-alpine
        environment:
            POSTGRES_PASSWORD: postgres
        networks:
            - backend

networks:
    backend:
